/// Flutter icons Newcamicon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Newcamicon
///      fonts:
///       - asset: fonts/Newcamicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Newcamicon {
  Newcamicon._();

  static const _kFontFam = 'Newcamicon';
  static const String? _kFontPkg = null;

  static const IconData clkmenu = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discount = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clkhome = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clkdiscount = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clkchat = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
